### ISSUE TITLE
Can't start remote_syslog

### ISSUE THREAD

**Issue by zmsmith** [papertrail/remote_syslog#6]
I receive this error on startup. I'm can't find where tag is being defined. `remote_syslog` was installed on Ubuntu 11.04 using `gem install remote_syslog`

Thanks.

Traceback below.

```
/usr/lib/ruby/gems/1.8/gems/syslog_protocol-0.9.0/lib/syslog_protocol/packet.rb:44:in `tag=': Tag must not be longer than 32 characters (ArgumentError)
    from /usr/lib/ruby/gems/1.8/gems/remote_syslog-1.1.0/lib/remote_syslog/reader.rb:32:in `initialize'
    from /usr/lib/ruby/gems/1.8/gems/eventmachine-tail-0.6.1/lib/em/filetail.rb:444:in `new'
    from /usr/lib/ruby/gems/1.8/gems/eventmachine-tail-0.6.1/lib/em/filetail.rb:444:in `file_tail'
    from /usr/lib/ruby/gems/1.8/gems/remote_syslog-1.1.0/bin/remote_syslog:103:in `remote_syslog_daemon'
    from /usr/lib/ruby/gems/1.8/gems/remote_syslog-1.1.0/bin/remote_syslog:101:in `each'
    from /usr/lib/ruby/gems/1.8/gems/remote_syslog-1.1.0/bin/remote_syslog:101:in `remote_syslog_daemon'
    from /usr/lib/ruby/gems/1.8/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in `call'
    from /usr/lib/ruby/gems/1.8/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in `run_machine'
    from /usr/lib/ruby/gems/1.8/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in `run'
    from /usr/lib/ruby/gems/1.8/gems/remote_syslog-1.1.0/bin/remote_syslog:98:in `remote_syslog_daemon'
    from /usr/lib/ruby/gems/1.8/gems/daemons-1.1.3/lib/daemons/application.rb:249:in `call'
    from /usr/lib/ruby/gems/1.8/gems/daemons-1.1.3/lib/daemons/application.rb:249:in `start_proc'
    from /usr/lib/ruby/gems/1.8/gems/daemons-1.1.3/lib/daemons/application.rb:260:in `call'
    from /usr/lib/ruby/gems/1.8/gems/daemons-1.1.3/lib/daemons/application.rb:260:in `start_proc'
    from /usr/lib/ruby/gems/1.8/gems/daemons-1.1.3/lib/daemons/application.rb:293:in `start'
    from /usr/lib/ruby/gems/1.8/gems/daemons-1.1.3/lib/daemons/controller.rb:73:in `run'
    from /usr/lib/ruby/gems/1.8/gems/daemons-1.1.3/lib/daemons.rb:195:in `run_proc'
    from /usr/lib/ruby/gems/1.8/gems/daemons-1.1.3/lib/daemons/cmdline.rb:109:in `call'
    from /usr/lib/ruby/gems/1.8/gems/daemons-1.1.3/lib/daemons/cmdline.rb:109:in `catch_exceptions'
    from /usr/lib/ruby/gems/1.8/gems/daemons-1.1.3/lib/daemons.rb:194:in `run_proc'
    from /usr/lib/ruby/gems/1.8/gems/remote_syslog-1.1.0/bin/remote_syslog:97:in `remote_syslog_daemon'
    from /usr/lib/ruby/gems/1.8/gems/remote_syslog-1.1.0/bin/remote_syslog:117
    from /usr/bin/remote_syslog:19:in `load'
    from /usr/bin/remote_syslog:19

```

**Comment by angelacode** [comment]
I have the error:
/home/nitrous/code/site/.bundle/gems/syslog_protocol-0.9.2/lib/syslog_protocol/packet.rb:49:in `tag=': Tag must not be longer than 32 characters (ArgumentError)

**Comment by angelacode** [comment]
I have filenames > 32 that seems to be causing the error

**Comment by eric** [comment]
What version of remote_syslog are you running? Have you considered using our newer version instead? 

It's available here: https://github.com/papertrail/remote_syslog2

**Comment by troy** [comment]
@angelacode The 32 character limit is set by [RFC 3164](https://tools.ietf.org/html/rfc3164), the protocol which the [remote_syslog_logger](https://github.com/papertrail/remote_syslog_logger) library implements. Specifically:

> The TAG is a string of ABNF alphanumeric characters that MUST NOT exceed 32 characters.

That said, if you're using this daemon, please upgrade to the much newer, better [remote_syslog2](https://github.com/papertrail/remote_syslog2) which @eric linked to above.
